spring.application.name=backend


# ------------------------------------------------------------------------------
# 1. MySQL Database Configuration
# ------------------------------------------------------------------------------

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ------------------------------------------------------------------------------
# 2. JWT (JSON Web Token) Configuration
# ------------------------------------------------------------------------------

jwt.secret=${JWT_SCRET}
jwt.expiration=${JWT_EXPIRATION}

# ------------------------------------------------------------------------------
# 3. Cloudinary Configuration (Profile Image Uploads)
# ------------------------------------------------------------------------------

cloudinary.cloud.name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_KEY}
cloudinary.api-secret=${CLOUDINARY_SECREAT}

# ------------------------------------------------------------------------------
# 4. Email / SMTP Configuration (Spring Mail)
# ------------------------------------------------------------------------------

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.from=${MAIL_FROM}

spring.mail.properties.mail.smtp.auth= true
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.protocol=smtp

# ------------------------------------------------------------------------------
# 5. Server & Application Settings (Optional Overrides)
# ------------------------------------------------------------------------------
server.port=${PORT:8080}
server.address=0.0.0.0
app.base.url=${BASE_URL}

#--------------------AI Provider Config (gemini or grok)-------------------
 
ai.provider=${AI_PROVIDER:gemini}
gemini.api.key=${GEMINI_KEY}
gemini.model=${GEMINI_MODEL}

grok.api.key=${GROK_API_KEY}
grok.model=${GROK_MODEL}
grok.api.url=${GROK_API_URL}



#App
app.base.url = ${BASE_URL}

spring.servlet.multipart.max-file-size=${FILE_SIZE}
spring.servlet.multipart.max-request-size=${FILE_SIZE}





